// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: activities.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countActivities = `-- name: CountActivities :one
SELECT COUNT(*)
FROM lead_activities a
WHERE a.user_id = $1
  AND ($2::uuid IS NULL OR a.lead_id = $2)
  AND ($3::uuid IS NULL OR a.company_id = $3)
  AND ($4::text IS NULL OR a.type = $4)
`

type CountActivitiesParams struct {
	UserID    uuid.UUID
	LeadID    *uuid.UUID
	CompanyID *uuid.UUID
	Type      pgtype.Text
}

func (q *Queries) CountActivities(ctx context.Context, arg CountActivitiesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countActivities,
		arg.UserID,
		arg.LeadID,
		arg.CompanyID,
		arg.Type,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createActivity = `-- name: CreateActivity :one
INSERT INTO lead_activities (user_id, lead_id, company_id, contact_id, type, description)
VALUES ($1, $4, $5, $6, $2, $3)
RETURNING id, user_id, lead_id, company_id, contact_id, type, description, created_at
`

type CreateActivityParams struct {
	UserID      uuid.UUID
	Type        string
	Description string
	LeadID      *uuid.UUID
	CompanyID   *uuid.UUID
	ContactID   *uuid.UUID
}

func (q *Queries) CreateActivity(ctx context.Context, arg CreateActivityParams) (LeadActivity, error) {
	row := q.db.QueryRow(ctx, createActivity,
		arg.UserID,
		arg.Type,
		arg.Description,
		arg.LeadID,
		arg.CompanyID,
		arg.ContactID,
	)
	var i LeadActivity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.LeadID,
		&i.CompanyID,
		&i.ContactID,
		&i.Type,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const deleteActivity = `-- name: DeleteActivity :exec
DELETE FROM lead_activities WHERE id = $1 AND user_id = $2
`

type DeleteActivityParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteActivity(ctx context.Context, arg DeleteActivityParams) error {
	_, err := q.db.Exec(ctx, deleteActivity, arg.ID, arg.UserID)
	return err
}

const getActivity = `-- name: GetActivity :one
SELECT a.id, a.user_id, a.lead_id, a.company_id, a.contact_id, a.type, a.description, a.created_at, c.name AS company_name FROM lead_activities a LEFT JOIN companies c ON c.id = a.company_id WHERE a.id = $1 AND a.user_id = $2
`

type GetActivityParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

type GetActivityRow struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	LeadID      *uuid.UUID
	CompanyID   *uuid.UUID
	ContactID   *uuid.UUID
	Type        string
	Description string
	CreatedAt   pgtype.Timestamptz
	CompanyName pgtype.Text
}

func (q *Queries) GetActivity(ctx context.Context, arg GetActivityParams) (GetActivityRow, error) {
	row := q.db.QueryRow(ctx, getActivity, arg.ID, arg.UserID)
	var i GetActivityRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.LeadID,
		&i.CompanyID,
		&i.ContactID,
		&i.Type,
		&i.Description,
		&i.CreatedAt,
		&i.CompanyName,
	)
	return i, err
}

const listActivities = `-- name: ListActivities :many
SELECT a.id, a.user_id, a.lead_id, a.company_id, a.contact_id, a.type, a.description, a.created_at, c.name AS company_name
FROM lead_activities a
LEFT JOIN companies c ON c.id = a.company_id
WHERE a.user_id = $1
  AND ($4::uuid IS NULL OR a.lead_id = $4)
  AND ($5::uuid IS NULL OR a.company_id = $5)
  AND ($6::text IS NULL OR a.type = $6)
  AND ($7::text IS NULL OR a.description ILIKE '%' || $7::text || '%')
ORDER BY a.created_at DESC
LIMIT $2 OFFSET $3
`

type ListActivitiesParams struct {
	UserID    uuid.UUID
	Limit     int32
	Offset    int32
	LeadID    *uuid.UUID
	CompanyID *uuid.UUID
	Type      pgtype.Text
	Search    pgtype.Text
}

type ListActivitiesRow struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	LeadID      *uuid.UUID
	CompanyID   *uuid.UUID
	ContactID   *uuid.UUID
	Type        string
	Description string
	CreatedAt   pgtype.Timestamptz
	CompanyName pgtype.Text
}

func (q *Queries) ListActivities(ctx context.Context, arg ListActivitiesParams) ([]ListActivitiesRow, error) {
	rows, err := q.db.Query(ctx, listActivities,
		arg.UserID,
		arg.Limit,
		arg.Offset,
		arg.LeadID,
		arg.CompanyID,
		arg.Type,
		arg.Search,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActivitiesRow
	for rows.Next() {
		var i ListActivitiesRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.LeadID,
			&i.CompanyID,
			&i.ContactID,
			&i.Type,
			&i.Description,
			&i.CreatedAt,
			&i.CompanyName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recentActivities = `-- name: RecentActivities :many
SELECT a.id, a.user_id, a.lead_id, a.company_id, a.contact_id, a.type, a.description, a.created_at, c.name AS company_name
FROM lead_activities a
LEFT JOIN companies c ON c.id = a.company_id
WHERE a.user_id = $1
ORDER BY a.created_at DESC
LIMIT $2
`

type RecentActivitiesParams struct {
	UserID uuid.UUID
	Limit  int32
}

type RecentActivitiesRow struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	LeadID      *uuid.UUID
	CompanyID   *uuid.UUID
	ContactID   *uuid.UUID
	Type        string
	Description string
	CreatedAt   pgtype.Timestamptz
	CompanyName pgtype.Text
}

func (q *Queries) RecentActivities(ctx context.Context, arg RecentActivitiesParams) ([]RecentActivitiesRow, error) {
	rows, err := q.db.Query(ctx, recentActivities, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RecentActivitiesRow
	for rows.Next() {
		var i RecentActivitiesRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.LeadID,
			&i.CompanyID,
			&i.ContactID,
			&i.Type,
			&i.Description,
			&i.CreatedAt,
			&i.CompanyName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchActivities = `-- name: SearchActivities :many
SELECT a.id, a.user_id, a.lead_id, a.company_id, a.contact_id, a.type, a.description, a.created_at, c.name AS company_name
FROM lead_activities a
LEFT JOIN companies c ON c.id = a.company_id
WHERE a.user_id = $1 AND a.description ILIKE '%' || $2 || '%'
ORDER BY a.created_at DESC LIMIT 10
`

type SearchActivitiesParams struct {
	UserID  uuid.UUID
	Column2 pgtype.Text
}

type SearchActivitiesRow struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	LeadID      *uuid.UUID
	CompanyID   *uuid.UUID
	ContactID   *uuid.UUID
	Type        string
	Description string
	CreatedAt   pgtype.Timestamptz
	CompanyName pgtype.Text
}

func (q *Queries) SearchActivities(ctx context.Context, arg SearchActivitiesParams) ([]SearchActivitiesRow, error) {
	rows, err := q.db.Query(ctx, searchActivities, arg.UserID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchActivitiesRow
	for rows.Next() {
		var i SearchActivitiesRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.LeadID,
			&i.CompanyID,
			&i.ContactID,
			&i.Type,
			&i.Description,
			&i.CreatedAt,
			&i.CompanyName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
