// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ai.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createAIAnalysis = `-- name: CreateAIAnalysis :one
INSERT INTO ai_analyses (user_id, lead_id, analysis)
VALUES ($1, $2, $3)
RETURNING id, user_id, lead_id, analysis, created_at
`

type CreateAIAnalysisParams struct {
	UserID   uuid.UUID
	LeadID   *uuid.UUID
	Analysis []byte
}

func (q *Queries) CreateAIAnalysis(ctx context.Context, arg CreateAIAnalysisParams) (AiAnalysis, error) {
	row := q.db.QueryRow(ctx, createAIAnalysis, arg.UserID, arg.LeadID, arg.Analysis)
	var i AiAnalysis
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.LeadID,
		&i.Analysis,
		&i.CreatedAt,
	)
	return i, err
}

const dashboardKPIs = `-- name: DashboardKPIs :one
SELECT
  (SELECT COUNT(*) FROM leads l WHERE l.user_id = $1)::int AS total_leads,
  (SELECT COUNT(*) FROM leads l WHERE l.user_id = $1 AND l.created_at >= now() - INTERVAL '7 days')::int AS new_leads,
  (SELECT COUNT(*) FROM follow_ups f WHERE f.user_id = $1 AND status = 'pending' AND due_date = CURRENT_DATE)::int AS followups_today,
  (SELECT COUNT(*) FROM follow_ups f WHERE f.user_id = $1 AND status = 'pending' AND due_date < CURRENT_DATE)::int AS followups_overdue,
  (SELECT COUNT(*) FROM leads l WHERE l.user_id = $1 AND status NOT IN ('won','lost','research'))::int AS active_deals,
  (SELECT COALESCE(SUM(l.estimated_value),0) FROM leads l WHERE l.user_id = $1 AND status NOT IN ('won','lost'))::float8 AS pipeline_value,
  (SELECT COALESCE(SUM(r.amount),0) FROM revenues r WHERE r.user_id = $1 AND occurred_at >= date_trunc('month', CURRENT_DATE))::float8 AS monthly_revenue,
  (SELECT COALESCE(SUM(
      CASE billing_cycle
        WHEN 'monthly' THEN amount
        WHEN 'quarterly' THEN amount / 3
        WHEN 'yearly' THEN amount / 12
        ELSE amount
      END),0)
   FROM recurring_services rs WHERE rs.user_id = $1 AND status = 'active')::float8 AS mrr
`

type DashboardKPIsRow struct {
	TotalLeads       int32
	NewLeads         int32
	FollowupsToday   int32
	FollowupsOverdue int32
	ActiveDeals      int32
	PipelineValue    float64
	MonthlyRevenue   float64
	Mrr              float64
}

func (q *Queries) DashboardKPIs(ctx context.Context, userID uuid.UUID) (DashboardKPIsRow, error) {
	row := q.db.QueryRow(ctx, dashboardKPIs, userID)
	var i DashboardKPIsRow
	err := row.Scan(
		&i.TotalLeads,
		&i.NewLeads,
		&i.FollowupsToday,
		&i.FollowupsOverdue,
		&i.ActiveDeals,
		&i.PipelineValue,
		&i.MonthlyRevenue,
		&i.Mrr,
	)
	return i, err
}

const latestAIAnalysis = `-- name: LatestAIAnalysis :one
SELECT id, user_id, lead_id, analysis, created_at FROM ai_analyses WHERE user_id = $1 AND lead_id = $2 ORDER BY created_at DESC LIMIT 1
`

type LatestAIAnalysisParams struct {
	UserID uuid.UUID
	LeadID *uuid.UUID
}

func (q *Queries) LatestAIAnalysis(ctx context.Context, arg LatestAIAnalysisParams) (AiAnalysis, error) {
	row := q.db.QueryRow(ctx, latestAIAnalysis, arg.UserID, arg.LeadID)
	var i AiAnalysis
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.LeadID,
		&i.Analysis,
		&i.CreatedAt,
	)
	return i, err
}
