// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: clients.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createClient = `-- name: CreateClient :one
INSERT INTO clients (user_id, company_id, contact_id, lead_id, status, notes, converted_at)
VALUES ($1, $2, $4, $5, $3, $6, now())
RETURNING id, user_id, company_id, contact_id, lead_id, status, notes, converted_at, created_at, updated_at
`

type CreateClientParams struct {
	UserID    uuid.UUID
	CompanyID uuid.UUID
	Status    string
	ContactID *uuid.UUID
	LeadID    *uuid.UUID
	Notes     pgtype.Text
}

func (q *Queries) CreateClient(ctx context.Context, arg CreateClientParams) (Client, error) {
	row := q.db.QueryRow(ctx, createClient,
		arg.UserID,
		arg.CompanyID,
		arg.Status,
		arg.ContactID,
		arg.LeadID,
		arg.Notes,
	)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CompanyID,
		&i.ContactID,
		&i.LeadID,
		&i.Status,
		&i.Notes,
		&i.ConvertedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteClient = `-- name: DeleteClient :exec
DELETE FROM clients WHERE id = $1 AND user_id = $2
`

type DeleteClientParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteClient(ctx context.Context, arg DeleteClientParams) error {
	_, err := q.db.Exec(ctx, deleteClient, arg.ID, arg.UserID)
	return err
}

const getClient = `-- name: GetClient :one
SELECT cl.id, cl.user_id, cl.company_id, cl.contact_id, cl.lead_id, cl.status, cl.notes, cl.converted_at, cl.created_at, cl.updated_at, c.name AS company_name
FROM clients cl
JOIN companies c ON c.id = cl.company_id
WHERE cl.id = $1 AND cl.user_id = $2
`

type GetClientParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

type GetClientRow struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	CompanyID   uuid.UUID
	ContactID   *uuid.UUID
	LeadID      *uuid.UUID
	Status      string
	Notes       pgtype.Text
	ConvertedAt pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	CompanyName string
}

func (q *Queries) GetClient(ctx context.Context, arg GetClientParams) (GetClientRow, error) {
	row := q.db.QueryRow(ctx, getClient, arg.ID, arg.UserID)
	var i GetClientRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CompanyID,
		&i.ContactID,
		&i.LeadID,
		&i.Status,
		&i.Notes,
		&i.ConvertedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompanyName,
	)
	return i, err
}

const listClients = `-- name: ListClients :many
SELECT cl.id, cl.user_id, cl.company_id, cl.contact_id, cl.lead_id, cl.status, cl.notes, cl.converted_at, cl.created_at, cl.updated_at, c.name AS company_name
FROM clients cl
JOIN companies c ON c.id = cl.company_id
WHERE cl.user_id = $1
  AND ($4::text IS NULL OR cl.status = $4)
  AND ($5::text IS NULL OR c.name ILIKE '%' || $5::text || '%')
ORDER BY cl.created_at DESC
LIMIT $2 OFFSET $3
`

type ListClientsParams struct {
	UserID uuid.UUID
	Limit  int32
	Offset int32
	Status pgtype.Text
	Search pgtype.Text
}

type ListClientsRow struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	CompanyID   uuid.UUID
	ContactID   *uuid.UUID
	LeadID      *uuid.UUID
	Status      string
	Notes       pgtype.Text
	ConvertedAt pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	CompanyName string
}

func (q *Queries) ListClients(ctx context.Context, arg ListClientsParams) ([]ListClientsRow, error) {
	rows, err := q.db.Query(ctx, listClients,
		arg.UserID,
		arg.Limit,
		arg.Offset,
		arg.Status,
		arg.Search,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListClientsRow
	for rows.Next() {
		var i ListClientsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CompanyID,
			&i.ContactID,
			&i.LeadID,
			&i.Status,
			&i.Notes,
			&i.ConvertedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompanyName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchClients = `-- name: SearchClients :many
SELECT cl.id, cl.user_id, cl.company_id, cl.contact_id, cl.lead_id, cl.status, cl.notes, cl.converted_at, cl.created_at, cl.updated_at, c.name AS company_name
FROM clients cl
JOIN companies c ON c.id = cl.company_id
WHERE cl.user_id = $1 AND c.name ILIKE '%' || $2 || '%'
ORDER BY cl.created_at DESC LIMIT 10
`

type SearchClientsParams struct {
	UserID  uuid.UUID
	Column2 pgtype.Text
}

type SearchClientsRow struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	CompanyID   uuid.UUID
	ContactID   *uuid.UUID
	LeadID      *uuid.UUID
	Status      string
	Notes       pgtype.Text
	ConvertedAt pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	CompanyName string
}

func (q *Queries) SearchClients(ctx context.Context, arg SearchClientsParams) ([]SearchClientsRow, error) {
	rows, err := q.db.Query(ctx, searchClients, arg.UserID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchClientsRow
	for rows.Next() {
		var i SearchClientsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CompanyID,
			&i.ContactID,
			&i.LeadID,
			&i.Status,
			&i.Notes,
			&i.ConvertedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompanyName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateClient = `-- name: UpdateClient :one
UPDATE clients SET
  status = COALESCE($1, status),
  notes  = COALESCE($2, notes),
  updated_at = now()
WHERE id = $3 AND user_id = $4
RETURNING id, user_id, company_id, contact_id, lead_id, status, notes, converted_at, created_at, updated_at
`

type UpdateClientParams struct {
	Status pgtype.Text
	Notes  pgtype.Text
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) UpdateClient(ctx context.Context, arg UpdateClientParams) (Client, error) {
	row := q.db.QueryRow(ctx, updateClient,
		arg.Status,
		arg.Notes,
		arg.ID,
		arg.UserID,
	)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CompanyID,
		&i.ContactID,
		&i.LeadID,
		&i.Status,
		&i.Notes,
		&i.ConvertedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
