// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: companies.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countCompanies = `-- name: CountCompanies :one
SELECT COUNT(*) FROM companies
WHERE user_id = $1
  AND ($2::text IS NULL OR name ILIKE '%' || $2::text || '%')
`

type CountCompaniesParams struct {
	UserID uuid.UUID
	Search pgtype.Text
}

func (q *Queries) CountCompanies(ctx context.Context, arg CountCompaniesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countCompanies, arg.UserID, arg.Search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCompany = `-- name: CreateCompany :one
INSERT INTO companies (user_id, name, website, industry, location, description, phone, email, notes, source)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, user_id, name, website, industry, location, description, phone, email, notes, source, created_at, updated_at
`

type CreateCompanyParams struct {
	UserID      uuid.UUID
	Name        string
	Website     pgtype.Text
	Industry    pgtype.Text
	Location    pgtype.Text
	Description pgtype.Text
	Phone       pgtype.Text
	Email       pgtype.Text
	Notes       pgtype.Text
	Source      pgtype.Text
}

func (q *Queries) CreateCompany(ctx context.Context, arg CreateCompanyParams) (Company, error) {
	row := q.db.QueryRow(ctx, createCompany,
		arg.UserID,
		arg.Name,
		arg.Website,
		arg.Industry,
		arg.Location,
		arg.Description,
		arg.Phone,
		arg.Email,
		arg.Notes,
		arg.Source,
	)
	var i Company
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Website,
		&i.Industry,
		&i.Location,
		&i.Description,
		&i.Phone,
		&i.Email,
		&i.Notes,
		&i.Source,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCompany = `-- name: DeleteCompany :exec
DELETE FROM companies WHERE id = $1 AND user_id = $2
`

type DeleteCompanyParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteCompany(ctx context.Context, arg DeleteCompanyParams) error {
	_, err := q.db.Exec(ctx, deleteCompany, arg.ID, arg.UserID)
	return err
}

const getCompany = `-- name: GetCompany :one
SELECT id, user_id, name, website, industry, location, description, phone, email, notes, source, created_at, updated_at FROM companies WHERE id = $1 AND user_id = $2
`

type GetCompanyParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) GetCompany(ctx context.Context, arg GetCompanyParams) (Company, error) {
	row := q.db.QueryRow(ctx, getCompany, arg.ID, arg.UserID)
	var i Company
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Website,
		&i.Industry,
		&i.Location,
		&i.Description,
		&i.Phone,
		&i.Email,
		&i.Notes,
		&i.Source,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCompanies = `-- name: ListCompanies :many
SELECT c.id, c.user_id, c.name, c.website, c.industry, c.location, c.description, c.phone, c.email, c.notes, c.source, c.created_at, c.updated_at
FROM companies c
WHERE c.user_id = $1
  AND ($4::text IS NULL OR c.name ILIKE '%' || $4::text || '%')
ORDER BY c.created_at DESC
LIMIT $2 OFFSET $3
`

type ListCompaniesParams struct {
	UserID uuid.UUID
	Limit  int32
	Offset int32
	Search pgtype.Text
}

func (q *Queries) ListCompanies(ctx context.Context, arg ListCompaniesParams) ([]Company, error) {
	rows, err := q.db.Query(ctx, listCompanies,
		arg.UserID,
		arg.Limit,
		arg.Offset,
		arg.Search,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Company
	for rows.Next() {
		var i Company
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Website,
			&i.Industry,
			&i.Location,
			&i.Description,
			&i.Phone,
			&i.Email,
			&i.Notes,
			&i.Source,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCompany = `-- name: UpdateCompany :one
UPDATE companies SET
  name        = COALESCE($1, name),
  website     = COALESCE($2, website),
  industry    = COALESCE($3, industry),
  location    = COALESCE($4, location),
  description = COALESCE($5, description),
  phone       = COALESCE($6, phone),
  email       = COALESCE($7, email),
  notes       = COALESCE($8, notes),
  updated_at  = now()
WHERE id = $9 AND user_id = $10
RETURNING id, user_id, name, website, industry, location, description, phone, email, notes, source, created_at, updated_at
`

type UpdateCompanyParams struct {
	Name        pgtype.Text
	Website     pgtype.Text
	Industry    pgtype.Text
	Location    pgtype.Text
	Description pgtype.Text
	Phone       pgtype.Text
	Email       pgtype.Text
	Notes       pgtype.Text
	ID          uuid.UUID
	UserID      uuid.UUID
}

func (q *Queries) UpdateCompany(ctx context.Context, arg UpdateCompanyParams) (Company, error) {
	row := q.db.QueryRow(ctx, updateCompany,
		arg.Name,
		arg.Website,
		arg.Industry,
		arg.Location,
		arg.Description,
		arg.Phone,
		arg.Email,
		arg.Notes,
		arg.ID,
		arg.UserID,
	)
	var i Company
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Website,
		&i.Industry,
		&i.Location,
		&i.Description,
		&i.Phone,
		&i.Email,
		&i.Notes,
		&i.Source,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
