// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: contacts.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createContact = `-- name: CreateContact :one
INSERT INTO contacts (user_id, company_id, name, job_title, email, phone, whatsapp, linkedin, notes)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, user_id, company_id, name, job_title, email, phone, whatsapp, linkedin, notes, created_at, updated_at
`

type CreateContactParams struct {
	UserID    uuid.UUID
	CompanyID uuid.UUID
	Name      string
	JobTitle  pgtype.Text
	Email     pgtype.Text
	Phone     pgtype.Text
	Whatsapp  pgtype.Text
	Linkedin  pgtype.Text
	Notes     pgtype.Text
}

func (q *Queries) CreateContact(ctx context.Context, arg CreateContactParams) (Contact, error) {
	row := q.db.QueryRow(ctx, createContact,
		arg.UserID,
		arg.CompanyID,
		arg.Name,
		arg.JobTitle,
		arg.Email,
		arg.Phone,
		arg.Whatsapp,
		arg.Linkedin,
		arg.Notes,
	)
	var i Contact
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CompanyID,
		&i.Name,
		&i.JobTitle,
		&i.Email,
		&i.Phone,
		&i.Whatsapp,
		&i.Linkedin,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteContact = `-- name: DeleteContact :exec
DELETE FROM contacts WHERE id = $1 AND user_id = $2
`

type DeleteContactParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteContact(ctx context.Context, arg DeleteContactParams) error {
	_, err := q.db.Exec(ctx, deleteContact, arg.ID, arg.UserID)
	return err
}

const getContact = `-- name: GetContact :one
SELECT id, user_id, company_id, name, job_title, email, phone, whatsapp, linkedin, notes, created_at, updated_at FROM contacts WHERE id = $1 AND user_id = $2
`

type GetContactParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) GetContact(ctx context.Context, arg GetContactParams) (Contact, error) {
	row := q.db.QueryRow(ctx, getContact, arg.ID, arg.UserID)
	var i Contact
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CompanyID,
		&i.Name,
		&i.JobTitle,
		&i.Email,
		&i.Phone,
		&i.Whatsapp,
		&i.Linkedin,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listContacts = `-- name: ListContacts :many
SELECT id, user_id, company_id, name, job_title, email, phone, whatsapp, linkedin, notes, created_at, updated_at FROM contacts WHERE user_id = $1 ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type ListContactsParams struct {
	UserID uuid.UUID
	Limit  int32
	Offset int32
}

func (q *Queries) ListContacts(ctx context.Context, arg ListContactsParams) ([]Contact, error) {
	rows, err := q.db.Query(ctx, listContacts, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Contact
	for rows.Next() {
		var i Contact
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CompanyID,
			&i.Name,
			&i.JobTitle,
			&i.Email,
			&i.Phone,
			&i.Whatsapp,
			&i.Linkedin,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContactsByCompany = `-- name: ListContactsByCompany :many
SELECT id, user_id, company_id, name, job_title, email, phone, whatsapp, linkedin, notes, created_at, updated_at FROM contacts WHERE user_id = $1 AND company_id = $2 ORDER BY created_at DESC
`

type ListContactsByCompanyParams struct {
	UserID    uuid.UUID
	CompanyID uuid.UUID
}

func (q *Queries) ListContactsByCompany(ctx context.Context, arg ListContactsByCompanyParams) ([]Contact, error) {
	rows, err := q.db.Query(ctx, listContactsByCompany, arg.UserID, arg.CompanyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Contact
	for rows.Next() {
		var i Contact
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CompanyID,
			&i.Name,
			&i.JobTitle,
			&i.Email,
			&i.Phone,
			&i.Whatsapp,
			&i.Linkedin,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchContacts = `-- name: SearchContacts :many
SELECT id, user_id, company_id, name, job_title, email, phone, whatsapp, linkedin, notes, created_at, updated_at FROM contacts WHERE user_id = $1 AND name ILIKE '%' || $2 || '%' ORDER BY created_at DESC LIMIT 20
`

type SearchContactsParams struct {
	UserID  uuid.UUID
	Column2 pgtype.Text
}

func (q *Queries) SearchContacts(ctx context.Context, arg SearchContactsParams) ([]Contact, error) {
	rows, err := q.db.Query(ctx, searchContacts, arg.UserID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Contact
	for rows.Next() {
		var i Contact
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CompanyID,
			&i.Name,
			&i.JobTitle,
			&i.Email,
			&i.Phone,
			&i.Whatsapp,
			&i.Linkedin,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateContact = `-- name: UpdateContact :one
UPDATE contacts SET
  name      = COALESCE($1, name),
  job_title = COALESCE($2, job_title),
  email     = COALESCE($3, email),
  phone     = COALESCE($4, phone),
  whatsapp  = COALESCE($5, whatsapp),
  linkedin  = COALESCE($6, linkedin),
  notes     = COALESCE($7, notes),
  updated_at = now()
WHERE id = $8 AND user_id = $9
RETURNING id, user_id, company_id, name, job_title, email, phone, whatsapp, linkedin, notes, created_at, updated_at
`

type UpdateContactParams struct {
	Name     pgtype.Text
	JobTitle pgtype.Text
	Email    pgtype.Text
	Phone    pgtype.Text
	Whatsapp pgtype.Text
	Linkedin pgtype.Text
	Notes    pgtype.Text
	ID       uuid.UUID
	UserID   uuid.UUID
}

func (q *Queries) UpdateContact(ctx context.Context, arg UpdateContactParams) (Contact, error) {
	row := q.db.QueryRow(ctx, updateContact,
		arg.Name,
		arg.JobTitle,
		arg.Email,
		arg.Phone,
		arg.Whatsapp,
		arg.Linkedin,
		arg.Notes,
		arg.ID,
		arg.UserID,
	)
	var i Contact
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CompanyID,
		&i.Name,
		&i.JobTitle,
		&i.Email,
		&i.Phone,
		&i.Whatsapp,
		&i.Linkedin,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
