// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: followups.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countFollowUps = `-- name: CountFollowUps :one
SELECT COUNT(*)
FROM follow_ups f
WHERE f.user_id = $1
  AND ($2::text IS NULL OR f.status = $2)
  AND (
    $3::text = 'all' OR $3::text IS NULL
    OR ($3::text = 'overdue' AND f.status = 'pending' AND f.due_date < CURRENT_DATE)
    OR ($3::text = 'today'   AND f.status = 'pending' AND f.due_date = CURRENT_DATE)
    OR ($3::text = 'upcoming' AND f.status = 'pending' AND f.due_date > CURRENT_DATE)
  )
`

type CountFollowUpsParams struct {
	UserID uuid.UUID
	Status pgtype.Text
	View   pgtype.Text
}

func (q *Queries) CountFollowUps(ctx context.Context, arg CountFollowUpsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countFollowUps, arg.UserID, arg.Status, arg.View)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createFollowUp = `-- name: CreateFollowUp :one
INSERT INTO follow_ups (user_id, lead_id, due_date, description)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, lead_id, due_date, description, status, completed_at, created_at
`

type CreateFollowUpParams struct {
	UserID      uuid.UUID
	LeadID      uuid.UUID
	DueDate     pgtype.Date
	Description pgtype.Text
}

func (q *Queries) CreateFollowUp(ctx context.Context, arg CreateFollowUpParams) (FollowUp, error) {
	row := q.db.QueryRow(ctx, createFollowUp,
		arg.UserID,
		arg.LeadID,
		arg.DueDate,
		arg.Description,
	)
	var i FollowUp
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.LeadID,
		&i.DueDate,
		&i.Description,
		&i.Status,
		&i.CompletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const followUpsToday = `-- name: FollowUpsToday :many
SELECT f.id, f.user_id, f.lead_id, f.due_date, f.description, f.status, f.completed_at, f.created_at, l.title AS lead_title, c.name AS company_name
FROM follow_ups f
JOIN leads l ON l.id = f.lead_id
JOIN companies c ON c.id = l.company_id
WHERE f.user_id = $1 AND f.status = 'pending' AND f.due_date <= CURRENT_DATE
ORDER BY f.due_date ASC LIMIT 50
`

type FollowUpsTodayRow struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	LeadID      uuid.UUID
	DueDate     pgtype.Date
	Description pgtype.Text
	Status      string
	CompletedAt pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
	LeadTitle   string
	CompanyName string
}

func (q *Queries) FollowUpsToday(ctx context.Context, userID uuid.UUID) ([]FollowUpsTodayRow, error) {
	rows, err := q.db.Query(ctx, followUpsToday, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FollowUpsTodayRow
	for rows.Next() {
		var i FollowUpsTodayRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.LeadID,
			&i.DueDate,
			&i.Description,
			&i.Status,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.LeadTitle,
			&i.CompanyName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFollowUp = `-- name: GetFollowUp :one
SELECT f.id, f.user_id, f.lead_id, f.due_date, f.description, f.status, f.completed_at, f.created_at, l.title AS lead_title, c.name AS company_name
FROM follow_ups f
JOIN leads l ON l.id = f.lead_id
JOIN companies c ON c.id = l.company_id
WHERE f.id = $1 AND f.user_id = $2
`

type GetFollowUpParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

type GetFollowUpRow struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	LeadID      uuid.UUID
	DueDate     pgtype.Date
	Description pgtype.Text
	Status      string
	CompletedAt pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
	LeadTitle   string
	CompanyName string
}

func (q *Queries) GetFollowUp(ctx context.Context, arg GetFollowUpParams) (GetFollowUpRow, error) {
	row := q.db.QueryRow(ctx, getFollowUp, arg.ID, arg.UserID)
	var i GetFollowUpRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.LeadID,
		&i.DueDate,
		&i.Description,
		&i.Status,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.LeadTitle,
		&i.CompanyName,
	)
	return i, err
}

const listFollowUps = `-- name: ListFollowUps :many
SELECT f.id, f.user_id, f.lead_id, f.due_date, f.description, f.status, f.completed_at, f.created_at, l.title AS lead_title, c.name AS company_name
FROM follow_ups f
JOIN leads l ON l.id = f.lead_id
JOIN companies c ON c.id = l.company_id
WHERE f.user_id = $1
  AND ($4::text IS NULL OR f.status = $4)
  AND (
    $5::text = 'all'
    OR ($5::text = 'overdue' AND f.status = 'pending' AND f.due_date < CURRENT_DATE)
    OR ($5::text = 'today'   AND f.status = 'pending' AND f.due_date = CURRENT_DATE)
    OR ($5::text = 'upcoming' AND f.status = 'pending' AND f.due_date > CURRENT_DATE)
  )
ORDER BY f.due_date ASC, f.created_at ASC
LIMIT $2 OFFSET $3
`

type ListFollowUpsParams struct {
	UserID uuid.UUID
	Limit  int32
	Offset int32
	Status pgtype.Text
	View   string
}

type ListFollowUpsRow struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	LeadID      uuid.UUID
	DueDate     pgtype.Date
	Description pgtype.Text
	Status      string
	CompletedAt pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
	LeadTitle   string
	CompanyName string
}

func (q *Queries) ListFollowUps(ctx context.Context, arg ListFollowUpsParams) ([]ListFollowUpsRow, error) {
	rows, err := q.db.Query(ctx, listFollowUps,
		arg.UserID,
		arg.Limit,
		arg.Offset,
		arg.Status,
		arg.View,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFollowUpsRow
	for rows.Next() {
		var i ListFollowUpsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.LeadID,
			&i.DueDate,
			&i.Description,
			&i.Status,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.LeadTitle,
			&i.CompanyName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFollowUp = `-- name: UpdateFollowUp :one
UPDATE follow_ups SET
  description  = COALESCE($1, description),
  status       = COALESCE($2, status),
  due_date     = COALESCE($3, due_date),
  completed_at = CASE
    WHEN $2::text = 'completed' THEN now()
    WHEN $2::text IN ('pending','cancelled') THEN NULL
    ELSE completed_at END
WHERE id = $4 AND user_id = $5
RETURNING id, user_id, lead_id, due_date, description, status, completed_at, created_at
`

type UpdateFollowUpParams struct {
	Description pgtype.Text
	Status      pgtype.Text
	DueDate     pgtype.Date
	ID          uuid.UUID
	UserID      uuid.UUID
}

func (q *Queries) UpdateFollowUp(ctx context.Context, arg UpdateFollowUpParams) (FollowUp, error) {
	row := q.db.QueryRow(ctx, updateFollowUp,
		arg.Description,
		arg.Status,
		arg.DueDate,
		arg.ID,
		arg.UserID,
	)
	var i FollowUp
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.LeadID,
		&i.DueDate,
		&i.Description,
		&i.Status,
		&i.CompletedAt,
		&i.CreatedAt,
	)
	return i, err
}
