// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: leads.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countLeads = `-- name: CountLeads :one
SELECT COUNT(*)
FROM leads l
JOIN companies c ON c.id = l.company_id
LEFT JOIN contacts ct ON ct.id = l.contact_id
WHERE l.user_id = $1
  AND ($2::text IS NULL OR l.status = $2)
  AND ($3::text IS NULL OR l.priority = $3)
  AND ($4::uuid IS NULL OR l.company_id = $4)
  AND ($5::text IS NULL OR l.title ILIKE '%' || $5::text || '%'
       OR c.name ILIKE '%' || $5::text || '%' OR ct.name ILIKE '%' || $5::text || '%')
`

type CountLeadsParams struct {
	UserID    uuid.UUID
	Status    pgtype.Text
	Priority  pgtype.Text
	CompanyID *uuid.UUID
	Search    pgtype.Text
}

func (q *Queries) CountLeads(ctx context.Context, arg CountLeadsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countLeads,
		arg.UserID,
		arg.Status,
		arg.Priority,
		arg.CompanyID,
		arg.Search,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createLead = `-- name: CreateLead :one
INSERT INTO leads (user_id, company_id, contact_id, title, status, priority, source, estimated_value, notes, next_follow_up)
VALUES ($1, $2, $6, $3, $4, $5, $7, $8, $9, $10)
RETURNING id, user_id, company_id, contact_id, title, status, priority, source, estimated_value, notes, next_follow_up, created_at, updated_at
`

type CreateLeadParams struct {
	UserID         uuid.UUID
	CompanyID      uuid.UUID
	Title          string
	Status         string
	Priority       string
	ContactID      *uuid.UUID
	Source         pgtype.Text
	EstimatedValue pgtype.Numeric
	Notes          pgtype.Text
	NextFollowUp   pgtype.Timestamptz
}

func (q *Queries) CreateLead(ctx context.Context, arg CreateLeadParams) (Lead, error) {
	row := q.db.QueryRow(ctx, createLead,
		arg.UserID,
		arg.CompanyID,
		arg.Title,
		arg.Status,
		arg.Priority,
		arg.ContactID,
		arg.Source,
		arg.EstimatedValue,
		arg.Notes,
		arg.NextFollowUp,
	)
	var i Lead
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CompanyID,
		&i.ContactID,
		&i.Title,
		&i.Status,
		&i.Priority,
		&i.Source,
		&i.EstimatedValue,
		&i.Notes,
		&i.NextFollowUp,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteLead = `-- name: DeleteLead :exec
DELETE FROM leads WHERE id = $1 AND user_id = $2
`

type DeleteLeadParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteLead(ctx context.Context, arg DeleteLeadParams) error {
	_, err := q.db.Exec(ctx, deleteLead, arg.ID, arg.UserID)
	return err
}

const getLead = `-- name: GetLead :one
SELECT id, user_id, company_id, contact_id, title, status, priority, source, estimated_value, notes, next_follow_up, created_at, updated_at FROM leads WHERE id = $1 AND user_id = $2
`

type GetLeadParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) GetLead(ctx context.Context, arg GetLeadParams) (Lead, error) {
	row := q.db.QueryRow(ctx, getLead, arg.ID, arg.UserID)
	var i Lead
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CompanyID,
		&i.ContactID,
		&i.Title,
		&i.Status,
		&i.Priority,
		&i.Source,
		&i.EstimatedValue,
		&i.Notes,
		&i.NextFollowUp,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const leadsForDashboard = `-- name: LeadsForDashboard :many
SELECT id, user_id, company_id, contact_id, title, status, priority, source, estimated_value, notes, next_follow_up, created_at, updated_at FROM leads
WHERE user_id = $1 AND status NOT IN ('won','lost')
ORDER BY created_at DESC LIMIT 200
`

func (q *Queries) LeadsForDashboard(ctx context.Context, userID uuid.UUID) ([]Lead, error) {
	rows, err := q.db.Query(ctx, leadsForDashboard, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Lead
	for rows.Next() {
		var i Lead
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CompanyID,
			&i.ContactID,
			&i.Title,
			&i.Status,
			&i.Priority,
			&i.Source,
			&i.EstimatedValue,
			&i.Notes,
			&i.NextFollowUp,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLeads = `-- name: ListLeads :many
SELECT l.id, l.user_id, l.company_id, l.contact_id, l.title, l.status, l.priority, l.source, l.estimated_value, l.notes, l.next_follow_up, l.created_at, l.updated_at, c.name AS company_name, ct.name AS contact_name
FROM leads l
JOIN companies c ON c.id = l.company_id
LEFT JOIN contacts ct ON ct.id = l.contact_id
WHERE l.user_id = $1
  AND ($4::text IS NULL OR l.status = $4)
  AND ($5::text IS NULL OR l.priority = $5)
  AND ($6::uuid IS NULL OR l.company_id = $6)
  AND ($7::text IS NULL OR l.title ILIKE '%' || $7::text || '%'
       OR c.name ILIKE '%' || $7::text || '%' OR ct.name ILIKE '%' || $7::text || '%')
ORDER BY
  CASE WHEN $8 = 'estimated_value' AND $9 = 'asc'  THEN l.estimated_value END ASC NULLS LAST,
  CASE WHEN $8 = 'estimated_value' AND $9 = 'desc' THEN l.estimated_value END DESC NULLS LAST,
  CASE WHEN $8 = 'title'           AND $9 = 'asc'  THEN l.title END ASC,
  CASE WHEN $8 = 'title'           AND $9 = 'desc' THEN l.title END DESC,
  CASE WHEN $8 NOT IN ('estimated_value','title') AND $9 = 'asc' THEN l.created_at END ASC,
  l.created_at DESC
LIMIT $2 OFFSET $3
`

type ListLeadsParams struct {
	UserID    uuid.UUID
	Limit     int32
	Offset    int32
	Status    pgtype.Text
	Priority  pgtype.Text
	CompanyID *uuid.UUID
	Search    pgtype.Text
	Sort      interface{}
	Order     interface{}
}

type ListLeadsRow struct {
	ID             uuid.UUID
	UserID         uuid.UUID
	CompanyID      uuid.UUID
	ContactID      *uuid.UUID
	Title          string
	Status         string
	Priority       string
	Source         pgtype.Text
	EstimatedValue pgtype.Numeric
	Notes          pgtype.Text
	NextFollowUp   pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	CompanyName    string
	ContactName    pgtype.Text
}

func (q *Queries) ListLeads(ctx context.Context, arg ListLeadsParams) ([]ListLeadsRow, error) {
	rows, err := q.db.Query(ctx, listLeads,
		arg.UserID,
		arg.Limit,
		arg.Offset,
		arg.Status,
		arg.Priority,
		arg.CompanyID,
		arg.Search,
		arg.Sort,
		arg.Order,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLeadsRow
	for rows.Next() {
		var i ListLeadsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CompanyID,
			&i.ContactID,
			&i.Title,
			&i.Status,
			&i.Priority,
			&i.Source,
			&i.EstimatedValue,
			&i.Notes,
			&i.NextFollowUp,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompanyName,
			&i.ContactName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pipelineByStatus = `-- name: PipelineByStatus :many
SELECT status, COUNT(*)::int AS count, COALESCE(SUM(estimated_value),0)::float8 AS value
FROM leads WHERE user_id = $1 GROUP BY status
`

type PipelineByStatusRow struct {
	Status string
	Count  int32
	Value  float64
}

func (q *Queries) PipelineByStatus(ctx context.Context, userID uuid.UUID) ([]PipelineByStatusRow, error) {
	rows, err := q.db.Query(ctx, pipelineByStatus, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PipelineByStatusRow
	for rows.Next() {
		var i PipelineByStatusRow
		if err := rows.Scan(&i.Status, &i.Count, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recentLeads = `-- name: RecentLeads :many
SELECT id, user_id, company_id, contact_id, title, status, priority, source, estimated_value, notes, next_follow_up, created_at, updated_at FROM leads WHERE user_id = $1 ORDER BY created_at DESC LIMIT $2
`

type RecentLeadsParams struct {
	UserID uuid.UUID
	Limit  int32
}

func (q *Queries) RecentLeads(ctx context.Context, arg RecentLeadsParams) ([]Lead, error) {
	rows, err := q.db.Query(ctx, recentLeads, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Lead
	for rows.Next() {
		var i Lead
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CompanyID,
			&i.ContactID,
			&i.Title,
			&i.Status,
			&i.Priority,
			&i.Source,
			&i.EstimatedValue,
			&i.Notes,
			&i.NextFollowUp,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLead = `-- name: UpdateLead :one
UPDATE leads SET
  contact_id      = $1,
  title           = COALESCE($2, title),
  status          = COALESCE($3, status),
  priority        = COALESCE($4, priority),
  source          = COALESCE($5, source),
  estimated_value = COALESCE($6, estimated_value),
  notes           = COALESCE($7, notes),
  next_follow_up  = COALESCE($8, next_follow_up),
  updated_at      = now()
WHERE id = $9 AND user_id = $10
RETURNING id, user_id, company_id, contact_id, title, status, priority, source, estimated_value, notes, next_follow_up, created_at, updated_at
`

type UpdateLeadParams struct {
	ContactID      *uuid.UUID
	Title          pgtype.Text
	Status         pgtype.Text
	Priority       pgtype.Text
	Source         pgtype.Text
	EstimatedValue pgtype.Numeric
	Notes          pgtype.Text
	NextFollowUp   pgtype.Timestamptz
	ID             uuid.UUID
	UserID         uuid.UUID
}

func (q *Queries) UpdateLead(ctx context.Context, arg UpdateLeadParams) (Lead, error) {
	row := q.db.QueryRow(ctx, updateLead,
		arg.ContactID,
		arg.Title,
		arg.Status,
		arg.Priority,
		arg.Source,
		arg.EstimatedValue,
		arg.Notes,
		arg.NextFollowUp,
		arg.ID,
		arg.UserID,
	)
	var i Lead
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CompanyID,
		&i.ContactID,
		&i.Title,
		&i.Status,
		&i.Priority,
		&i.Source,
		&i.EstimatedValue,
		&i.Notes,
		&i.NextFollowUp,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateLeadStatus = `-- name: UpdateLeadStatus :one
UPDATE leads SET status = $3, updated_at = now() WHERE id = $1 AND user_id = $2 RETURNING id, user_id, company_id, contact_id, title, status, priority, source, estimated_value, notes, next_follow_up, created_at, updated_at
`

type UpdateLeadStatusParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
	Status string
}

func (q *Queries) UpdateLeadStatus(ctx context.Context, arg UpdateLeadStatusParams) (Lead, error) {
	row := q.db.QueryRow(ctx, updateLeadStatus, arg.ID, arg.UserID, arg.Status)
	var i Lead
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CompanyID,
		&i.ContactID,
		&i.Title,
		&i.Status,
		&i.Priority,
		&i.Source,
		&i.EstimatedValue,
		&i.Notes,
		&i.NextFollowUp,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
