// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AiAnalysis struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	LeadID    *uuid.UUID
	Analysis  []byte
	CreatedAt pgtype.Timestamptz
}

type Client struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	CompanyID   uuid.UUID
	ContactID   *uuid.UUID
	LeadID      *uuid.UUID
	Status      string
	Notes       pgtype.Text
	ConvertedAt pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type Company struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	Name        string
	Website     pgtype.Text
	Industry    pgtype.Text
	Location    pgtype.Text
	Description pgtype.Text
	Phone       pgtype.Text
	Email       pgtype.Text
	Notes       pgtype.Text
	Source      pgtype.Text
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type Contact struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	CompanyID uuid.UUID
	Name      string
	JobTitle  pgtype.Text
	Email     pgtype.Text
	Phone     pgtype.Text
	Whatsapp  pgtype.Text
	Linkedin  pgtype.Text
	Notes     pgtype.Text
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type FollowUp struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	LeadID      uuid.UUID
	DueDate     pgtype.Date
	Description pgtype.Text
	Status      string
	CompletedAt pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
}

type Lead struct {
	ID             uuid.UUID
	UserID         uuid.UUID
	CompanyID      uuid.UUID
	ContactID      *uuid.UUID
	Title          string
	Status         string
	Priority       string
	Source         pgtype.Text
	EstimatedValue pgtype.Numeric
	Notes          pgtype.Text
	NextFollowUp   pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type LeadActivity struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	LeadID      *uuid.UUID
	CompanyID   *uuid.UUID
	ContactID   *uuid.UUID
	Type        string
	Description string
	CreatedAt   pgtype.Timestamptz
}

type Notification struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Type      string
	Title     string
	Body      pgtype.Text
	Link      pgtype.Text
	ReadAt    pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type OutreachTemplate struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Name      string
	Category  string
	Channel   string
	Body      string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Project struct {
	ID            uuid.UUID
	UserID        uuid.UUID
	ClientID      uuid.UUID
	Name          string
	Description   pgtype.Text
	Status        string
	StartDate     pgtype.Date
	EndDate       pgtype.Date
	Budget        pgtype.Numeric
	ActualRevenue pgtype.Numeric
	Notes         pgtype.Text
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

type Proposal struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	LeadID      uuid.UUID
	CompanyID   *uuid.UUID
	Title       string
	Description pgtype.Text
	Amount      pgtype.Numeric
	Status      string
	SentAt      pgtype.Timestamptz
	ValidUntil  pgtype.Date
	Notes       pgtype.Text
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type RecurringService struct {
	ID              uuid.UUID
	UserID          uuid.UUID
	ClientID        uuid.UUID
	ProjectID       *uuid.UUID
	Name            string
	Amount          pgtype.Numeric
	BillingCycle    string
	StartDate       pgtype.Date
	NextBillingDate pgtype.Date
	Status          string
	Notes           pgtype.Text
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type RefreshToken struct {
	Token     uuid.UUID
	UserID    uuid.UUID
	ExpiresAt pgtype.Timestamptz
	RevokedAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type ResearchRecord struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	Industry    pgtype.Text
	Location    pgtype.Text
	Keyword     pgtype.Text
	CompanyName pgtype.Text
	Website     pgtype.Text
	Description pgtype.Text
	PainPoint   pgtype.Text
	Opportunity pgtype.Text
	Service     pgtype.Text
	Priority    pgtype.Text
	Notes       pgtype.Text
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type Revenue struct {
	ID                 uuid.UUID
	UserID             uuid.UUID
	ClientID           *uuid.UUID
	ProjectID          *uuid.UUID
	RecurringServiceID *uuid.UUID
	Amount             pgtype.Numeric
	Type               string
	OccurredAt         pgtype.Date
	Notes              pgtype.Text
	CreatedAt          pgtype.Timestamptz
}

type User struct {
	ID           uuid.UUID
	Name         string
	Email        string
	PasswordHash string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}
