// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notifications.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countNotifications = `-- name: CountNotifications :one
SELECT COUNT(*) FROM notifications WHERE user_id = $1
`

func (q *Queries) CountNotifications(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countNotifications, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createNotification = `-- name: CreateNotification :one
INSERT INTO notifications (user_id, type, title, body, link)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, type, title, body, link, read_at, created_at
`

type CreateNotificationParams struct {
	UserID uuid.UUID
	Type   string
	Title  string
	Body   pgtype.Text
	Link   pgtype.Text
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error) {
	row := q.db.QueryRow(ctx, createNotification,
		arg.UserID,
		arg.Type,
		arg.Title,
		arg.Body,
		arg.Link,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Title,
		&i.Body,
		&i.Link,
		&i.ReadAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteNotification = `-- name: DeleteNotification :exec
DELETE FROM notifications WHERE id = $1 AND user_id = $2
`

type DeleteNotificationParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteNotification(ctx context.Context, arg DeleteNotificationParams) error {
	_, err := q.db.Exec(ctx, deleteNotification, arg.ID, arg.UserID)
	return err
}

const dueFollowUpsForUser = `-- name: DueFollowUpsForUser :many
SELECT f.id, f.user_id, f.lead_id, f.due_date, f.description, f.status, f.completed_at, f.created_at, l.title AS lead_title, c.name AS company_name
FROM follow_ups f
JOIN leads l ON l.id = f.lead_id
JOIN companies c ON c.id = l.company_id
WHERE f.user_id = $1 AND f.status = 'pending' AND f.due_date <= CURRENT_DATE
`

type DueFollowUpsForUserRow struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	LeadID      uuid.UUID
	DueDate     pgtype.Date
	Description pgtype.Text
	Status      string
	CompletedAt pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
	LeadTitle   string
	CompanyName string
}

func (q *Queries) DueFollowUpsForUser(ctx context.Context, userID uuid.UUID) ([]DueFollowUpsForUserRow, error) {
	rows, err := q.db.Query(ctx, dueFollowUpsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DueFollowUpsForUserRow
	for rows.Next() {
		var i DueFollowUpsForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.LeadID,
			&i.DueDate,
			&i.Description,
			&i.Status,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.LeadTitle,
			&i.CompanyName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotifications = `-- name: ListNotifications :many
SELECT id, user_id, type, title, body, link, read_at, created_at FROM notifications WHERE user_id = $1 ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type ListNotificationsParams struct {
	UserID uuid.UUID
	Limit  int32
	Offset int32
}

func (q *Queries) ListNotifications(ctx context.Context, arg ListNotificationsParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, listNotifications, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Notification
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.Title,
			&i.Body,
			&i.Link,
			&i.ReadAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserIDs = `-- name: ListUserIDs :many
SELECT id FROM users
`

func (q *Queries) ListUserIDs(ctx context.Context) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listUserIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllNotificationsRead = `-- name: MarkAllNotificationsRead :exec
UPDATE notifications SET read_at = now() WHERE user_id = $1 AND read_at IS NULL
`

func (q *Queries) MarkAllNotificationsRead(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, markAllNotificationsRead, userID)
	return err
}

const markNotificationRead = `-- name: MarkNotificationRead :one
UPDATE notifications SET read_at = now() WHERE id = $1 AND user_id = $2 RETURNING id, user_id, type, title, body, link, read_at, created_at
`

type MarkNotificationReadParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) MarkNotificationRead(ctx context.Context, arg MarkNotificationReadParams) (Notification, error) {
	row := q.db.QueryRow(ctx, markNotificationRead, arg.ID, arg.UserID)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Title,
		&i.Body,
		&i.Link,
		&i.ReadAt,
		&i.CreatedAt,
	)
	return i, err
}

const unreadNotificationCount = `-- name: UnreadNotificationCount :one
SELECT COUNT(*)::int AS unread FROM notifications WHERE user_id = $1 AND read_at IS NULL
`

func (q *Queries) UnreadNotificationCount(ctx context.Context, userID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, unreadNotificationCount, userID)
	var unread int32
	err := row.Scan(&unread)
	return unread, err
}
