// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: projects.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createProject = `-- name: CreateProject :one
INSERT INTO projects (user_id, client_id, name, description, status, start_date, end_date, budget, notes)
VALUES ($1, $2, $3, $5, $4, $6, $7, $8, $9)
RETURNING id, user_id, client_id, name, description, status, start_date, end_date, budget, actual_revenue, notes, created_at, updated_at
`

type CreateProjectParams struct {
	UserID      uuid.UUID
	ClientID    uuid.UUID
	Name        string
	Status      string
	Description pgtype.Text
	StartDate   pgtype.Date
	EndDate     pgtype.Date
	Budget      pgtype.Numeric
	Notes       pgtype.Text
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject,
		arg.UserID,
		arg.ClientID,
		arg.Name,
		arg.Status,
		arg.Description,
		arg.StartDate,
		arg.EndDate,
		arg.Budget,
		arg.Notes,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ClientID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.StartDate,
		&i.EndDate,
		&i.Budget,
		&i.ActualRevenue,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProject = `-- name: DeleteProject :exec
DELETE FROM projects WHERE id = $1 AND user_id = $2
`

type DeleteProjectParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteProject(ctx context.Context, arg DeleteProjectParams) error {
	_, err := q.db.Exec(ctx, deleteProject, arg.ID, arg.UserID)
	return err
}

const getProject = `-- name: GetProject :one
SELECT p.id, p.user_id, p.client_id, p.name, p.description, p.status, p.start_date, p.end_date, p.budget, p.actual_revenue, p.notes, p.created_at, p.updated_at, c.name AS client_company
FROM projects p
JOIN clients cl ON cl.id = p.client_id
JOIN companies c ON c.id = cl.company_id
WHERE p.id = $1 AND p.user_id = $2
`

type GetProjectParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

type GetProjectRow struct {
	ID            uuid.UUID
	UserID        uuid.UUID
	ClientID      uuid.UUID
	Name          string
	Description   pgtype.Text
	Status        string
	StartDate     pgtype.Date
	EndDate       pgtype.Date
	Budget        pgtype.Numeric
	ActualRevenue pgtype.Numeric
	Notes         pgtype.Text
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	ClientCompany string
}

func (q *Queries) GetProject(ctx context.Context, arg GetProjectParams) (GetProjectRow, error) {
	row := q.db.QueryRow(ctx, getProject, arg.ID, arg.UserID)
	var i GetProjectRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ClientID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.StartDate,
		&i.EndDate,
		&i.Budget,
		&i.ActualRevenue,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClientCompany,
	)
	return i, err
}

const listProjects = `-- name: ListProjects :many
SELECT p.id, p.user_id, p.client_id, p.name, p.description, p.status, p.start_date, p.end_date, p.budget, p.actual_revenue, p.notes, p.created_at, p.updated_at, c.name AS client_company
FROM projects p
JOIN clients cl ON cl.id = p.client_id
JOIN companies c ON c.id = cl.company_id
WHERE p.user_id = $1
  AND ($4::text IS NULL OR p.status = $4)
  AND ($5::uuid IS NULL OR p.client_id = $5)
  AND ($6::text IS NULL OR p.name ILIKE '%' || $6::text || '%')
ORDER BY p.created_at DESC
LIMIT $2 OFFSET $3
`

type ListProjectsParams struct {
	UserID   uuid.UUID
	Limit    int32
	Offset   int32
	Status   pgtype.Text
	ClientID *uuid.UUID
	Search   pgtype.Text
}

type ListProjectsRow struct {
	ID            uuid.UUID
	UserID        uuid.UUID
	ClientID      uuid.UUID
	Name          string
	Description   pgtype.Text
	Status        string
	StartDate     pgtype.Date
	EndDate       pgtype.Date
	Budget        pgtype.Numeric
	ActualRevenue pgtype.Numeric
	Notes         pgtype.Text
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	ClientCompany string
}

func (q *Queries) ListProjects(ctx context.Context, arg ListProjectsParams) ([]ListProjectsRow, error) {
	rows, err := q.db.Query(ctx, listProjects,
		arg.UserID,
		arg.Limit,
		arg.Offset,
		arg.Status,
		arg.ClientID,
		arg.Search,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProjectsRow
	for rows.Next() {
		var i ListProjectsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ClientID,
			&i.Name,
			&i.Description,
			&i.Status,
			&i.StartDate,
			&i.EndDate,
			&i.Budget,
			&i.ActualRevenue,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ClientCompany,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchProjects = `-- name: SearchProjects :many
SELECT p.id, p.user_id, p.client_id, p.name, p.description, p.status, p.start_date, p.end_date, p.budget, p.actual_revenue, p.notes, p.created_at, p.updated_at, c.name AS client_company
FROM projects p
JOIN clients cl ON cl.id = p.client_id
JOIN companies c ON c.id = cl.company_id
WHERE p.user_id = $1 AND p.name ILIKE '%' || $2 || '%'
ORDER BY p.created_at DESC LIMIT 10
`

type SearchProjectsParams struct {
	UserID  uuid.UUID
	Column2 pgtype.Text
}

type SearchProjectsRow struct {
	ID            uuid.UUID
	UserID        uuid.UUID
	ClientID      uuid.UUID
	Name          string
	Description   pgtype.Text
	Status        string
	StartDate     pgtype.Date
	EndDate       pgtype.Date
	Budget        pgtype.Numeric
	ActualRevenue pgtype.Numeric
	Notes         pgtype.Text
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	ClientCompany string
}

func (q *Queries) SearchProjects(ctx context.Context, arg SearchProjectsParams) ([]SearchProjectsRow, error) {
	rows, err := q.db.Query(ctx, searchProjects, arg.UserID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchProjectsRow
	for rows.Next() {
		var i SearchProjectsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ClientID,
			&i.Name,
			&i.Description,
			&i.Status,
			&i.StartDate,
			&i.EndDate,
			&i.Budget,
			&i.ActualRevenue,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ClientCompany,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProject = `-- name: UpdateProject :one
UPDATE projects SET
  name           = COALESCE($1, name),
  description    = COALESCE($2, description),
  status         = COALESCE($3, status),
  start_date     = COALESCE($4, start_date),
  end_date       = COALESCE($5, end_date),
  budget         = COALESCE($6, budget),
  actual_revenue = COALESCE($7, actual_revenue),
  notes          = COALESCE($8, notes),
  updated_at     = now()
WHERE id = $9 AND user_id = $10
RETURNING id, user_id, client_id, name, description, status, start_date, end_date, budget, actual_revenue, notes, created_at, updated_at
`

type UpdateProjectParams struct {
	Name          pgtype.Text
	Description   pgtype.Text
	Status        pgtype.Text
	StartDate     pgtype.Date
	EndDate       pgtype.Date
	Budget        pgtype.Numeric
	ActualRevenue pgtype.Numeric
	Notes         pgtype.Text
	ID            uuid.UUID
	UserID        uuid.UUID
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, updateProject,
		arg.Name,
		arg.Description,
		arg.Status,
		arg.StartDate,
		arg.EndDate,
		arg.Budget,
		arg.ActualRevenue,
		arg.Notes,
		arg.ID,
		arg.UserID,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ClientID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.StartDate,
		&i.EndDate,
		&i.Budget,
		&i.ActualRevenue,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
