// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: proposals.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createProposal = `-- name: CreateProposal :one
INSERT INTO proposals (user_id, lead_id, company_id, title, description, amount, status, sent_at, valid_until, notes)
VALUES ($1, $2, $6, $3, $7, $4, $5, $8, $9, $10)
RETURNING id, user_id, lead_id, company_id, title, description, amount, status, sent_at, valid_until, notes, created_at, updated_at
`

type CreateProposalParams struct {
	UserID      uuid.UUID
	LeadID      uuid.UUID
	Title       string
	Amount      pgtype.Numeric
	Status      string
	CompanyID   *uuid.UUID
	Description pgtype.Text
	SentAt      pgtype.Timestamptz
	ValidUntil  pgtype.Date
	Notes       pgtype.Text
}

func (q *Queries) CreateProposal(ctx context.Context, arg CreateProposalParams) (Proposal, error) {
	row := q.db.QueryRow(ctx, createProposal,
		arg.UserID,
		arg.LeadID,
		arg.Title,
		arg.Amount,
		arg.Status,
		arg.CompanyID,
		arg.Description,
		arg.SentAt,
		arg.ValidUntil,
		arg.Notes,
	)
	var i Proposal
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.LeadID,
		&i.CompanyID,
		&i.Title,
		&i.Description,
		&i.Amount,
		&i.Status,
		&i.SentAt,
		&i.ValidUntil,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProposal = `-- name: DeleteProposal :exec
DELETE FROM proposals WHERE id = $1 AND user_id = $2
`

type DeleteProposalParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteProposal(ctx context.Context, arg DeleteProposalParams) error {
	_, err := q.db.Exec(ctx, deleteProposal, arg.ID, arg.UserID)
	return err
}

const getProposal = `-- name: GetProposal :one
SELECT p.id, p.user_id, p.lead_id, p.company_id, p.title, p.description, p.amount, p.status, p.sent_at, p.valid_until, p.notes, p.created_at, p.updated_at, c.name AS company_name, l.title AS lead_title
FROM proposals p
JOIN leads l ON l.id = p.lead_id
LEFT JOIN companies c ON c.id = p.company_id
WHERE p.id = $1 AND p.user_id = $2
`

type GetProposalParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

type GetProposalRow struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	LeadID      uuid.UUID
	CompanyID   *uuid.UUID
	Title       string
	Description pgtype.Text
	Amount      pgtype.Numeric
	Status      string
	SentAt      pgtype.Timestamptz
	ValidUntil  pgtype.Date
	Notes       pgtype.Text
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	CompanyName pgtype.Text
	LeadTitle   string
}

func (q *Queries) GetProposal(ctx context.Context, arg GetProposalParams) (GetProposalRow, error) {
	row := q.db.QueryRow(ctx, getProposal, arg.ID, arg.UserID)
	var i GetProposalRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.LeadID,
		&i.CompanyID,
		&i.Title,
		&i.Description,
		&i.Amount,
		&i.Status,
		&i.SentAt,
		&i.ValidUntil,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompanyName,
		&i.LeadTitle,
	)
	return i, err
}

const listProposals = `-- name: ListProposals :many
SELECT p.id, p.user_id, p.lead_id, p.company_id, p.title, p.description, p.amount, p.status, p.sent_at, p.valid_until, p.notes, p.created_at, p.updated_at, c.name AS company_name, l.title AS lead_title
FROM proposals p
JOIN leads l ON l.id = p.lead_id
LEFT JOIN companies c ON c.id = p.company_id
WHERE p.user_id = $1
  AND ($4::text IS NULL OR p.status = $4)
  AND ($5::uuid IS NULL OR p.lead_id = $5)
ORDER BY p.created_at DESC
LIMIT $2 OFFSET $3
`

type ListProposalsParams struct {
	UserID uuid.UUID
	Limit  int32
	Offset int32
	Status pgtype.Text
	LeadID *uuid.UUID
}

type ListProposalsRow struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	LeadID      uuid.UUID
	CompanyID   *uuid.UUID
	Title       string
	Description pgtype.Text
	Amount      pgtype.Numeric
	Status      string
	SentAt      pgtype.Timestamptz
	ValidUntil  pgtype.Date
	Notes       pgtype.Text
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	CompanyName pgtype.Text
	LeadTitle   string
}

func (q *Queries) ListProposals(ctx context.Context, arg ListProposalsParams) ([]ListProposalsRow, error) {
	rows, err := q.db.Query(ctx, listProposals,
		arg.UserID,
		arg.Limit,
		arg.Offset,
		arg.Status,
		arg.LeadID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProposalsRow
	for rows.Next() {
		var i ListProposalsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.LeadID,
			&i.CompanyID,
			&i.Title,
			&i.Description,
			&i.Amount,
			&i.Status,
			&i.SentAt,
			&i.ValidUntil,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompanyName,
			&i.LeadTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const proposalsNearExpiry = `-- name: ProposalsNearExpiry :many
SELECT p.id, p.user_id, p.lead_id, p.company_id, p.title, p.description, p.amount, p.status, p.sent_at, p.valid_until, p.notes, p.created_at, p.updated_at, c.name AS company_name, l.title AS lead_title
FROM proposals p
JOIN leads l ON l.id = p.lead_id
LEFT JOIN companies c ON c.id = p.company_id
WHERE p.user_id = $1 AND p.status IN ('sent','negotiation')
  AND p.valid_until IS NOT NULL
  AND p.valid_until BETWEEN CURRENT_DATE AND CURRENT_DATE + INTERVAL '3 days'
ORDER BY p.valid_until ASC LIMIT 20
`

type ProposalsNearExpiryRow struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	LeadID      uuid.UUID
	CompanyID   *uuid.UUID
	Title       string
	Description pgtype.Text
	Amount      pgtype.Numeric
	Status      string
	SentAt      pgtype.Timestamptz
	ValidUntil  pgtype.Date
	Notes       pgtype.Text
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	CompanyName pgtype.Text
	LeadTitle   string
}

func (q *Queries) ProposalsNearExpiry(ctx context.Context, userID uuid.UUID) ([]ProposalsNearExpiryRow, error) {
	rows, err := q.db.Query(ctx, proposalsNearExpiry, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProposalsNearExpiryRow
	for rows.Next() {
		var i ProposalsNearExpiryRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.LeadID,
			&i.CompanyID,
			&i.Title,
			&i.Description,
			&i.Amount,
			&i.Status,
			&i.SentAt,
			&i.ValidUntil,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompanyName,
			&i.LeadTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProposal = `-- name: UpdateProposal :one
UPDATE proposals SET
  title       = COALESCE($1, title),
  description = COALESCE($2, description),
  amount      = COALESCE($3, amount),
  status      = COALESCE($4, status),
  sent_at     = CASE WHEN $4::text = 'sent' AND sent_at IS NULL THEN now() ELSE sent_at END,
  valid_until = COALESCE($5, valid_until),
  notes       = COALESCE($6, notes),
  updated_at  = now()
WHERE id = $7 AND user_id = $8
RETURNING id, user_id, lead_id, company_id, title, description, amount, status, sent_at, valid_until, notes, created_at, updated_at
`

type UpdateProposalParams struct {
	Title       pgtype.Text
	Description pgtype.Text
	Amount      pgtype.Numeric
	Status      pgtype.Text
	ValidUntil  pgtype.Date
	Notes       pgtype.Text
	ID          uuid.UUID
	UserID      uuid.UUID
}

func (q *Queries) UpdateProposal(ctx context.Context, arg UpdateProposalParams) (Proposal, error) {
	row := q.db.QueryRow(ctx, updateProposal,
		arg.Title,
		arg.Description,
		arg.Amount,
		arg.Status,
		arg.ValidUntil,
		arg.Notes,
		arg.ID,
		arg.UserID,
	)
	var i Proposal
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.LeadID,
		&i.CompanyID,
		&i.Title,
		&i.Description,
		&i.Amount,
		&i.Status,
		&i.SentAt,
		&i.ValidUntil,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
