// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	ActiveRecurringForMRR(ctx context.Context, userID uuid.UUID) ([]ActiveRecurringForMRRRow, error)
	CountActivities(ctx context.Context, arg CountActivitiesParams) (int64, error)
	CountCompanies(ctx context.Context, arg CountCompaniesParams) (int64, error)
	CountFollowUps(ctx context.Context, arg CountFollowUpsParams) (int64, error)
	CountLeads(ctx context.Context, arg CountLeadsParams) (int64, error)
	CountNotifications(ctx context.Context, userID uuid.UUID) (int64, error)
	CountRevenues(ctx context.Context, arg CountRevenuesParams) (int64, error)
	CreateAIAnalysis(ctx context.Context, arg CreateAIAnalysisParams) (AiAnalysis, error)
	CreateActivity(ctx context.Context, arg CreateActivityParams) (LeadActivity, error)
	CreateClient(ctx context.Context, arg CreateClientParams) (Client, error)
	CreateCompany(ctx context.Context, arg CreateCompanyParams) (Company, error)
	CreateContact(ctx context.Context, arg CreateContactParams) (Contact, error)
	CreateFollowUp(ctx context.Context, arg CreateFollowUpParams) (FollowUp, error)
	CreateLead(ctx context.Context, arg CreateLeadParams) (Lead, error)
	CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error)
	CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error)
	CreateProposal(ctx context.Context, arg CreateProposalParams) (Proposal, error)
	CreateRecurringService(ctx context.Context, arg CreateRecurringServiceParams) (RecurringService, error)
	CreateResearch(ctx context.Context, arg CreateResearchParams) (ResearchRecord, error)
	CreateRevenue(ctx context.Context, arg CreateRevenueParams) (Revenue, error)
	CreateTemplate(ctx context.Context, arg CreateTemplateParams) (OutreachTemplate, error)
	DashboardKPIs(ctx context.Context, userID uuid.UUID) (DashboardKPIsRow, error)
	DeleteActivity(ctx context.Context, arg DeleteActivityParams) error
	DeleteClient(ctx context.Context, arg DeleteClientParams) error
	DeleteCompany(ctx context.Context, arg DeleteCompanyParams) error
	DeleteContact(ctx context.Context, arg DeleteContactParams) error
	DeleteLead(ctx context.Context, arg DeleteLeadParams) error
	DeleteNotification(ctx context.Context, arg DeleteNotificationParams) error
	DeleteProject(ctx context.Context, arg DeleteProjectParams) error
	DeleteProposal(ctx context.Context, arg DeleteProposalParams) error
	DeleteRecurringService(ctx context.Context, arg DeleteRecurringServiceParams) error
	DeleteResearch(ctx context.Context, arg DeleteResearchParams) error
	DeleteRevenue(ctx context.Context, arg DeleteRevenueParams) error
	DeleteTemplate(ctx context.Context, arg DeleteTemplateParams) error
	DueFollowUpsForUser(ctx context.Context, userID uuid.UUID) ([]DueFollowUpsForUserRow, error)
	FollowUpsToday(ctx context.Context, userID uuid.UUID) ([]FollowUpsTodayRow, error)
	GetActivity(ctx context.Context, arg GetActivityParams) (GetActivityRow, error)
	GetClient(ctx context.Context, arg GetClientParams) (GetClientRow, error)
	GetCompany(ctx context.Context, arg GetCompanyParams) (Company, error)
	GetContact(ctx context.Context, arg GetContactParams) (Contact, error)
	GetFollowUp(ctx context.Context, arg GetFollowUpParams) (GetFollowUpRow, error)
	GetLead(ctx context.Context, arg GetLeadParams) (Lead, error)
	GetProject(ctx context.Context, arg GetProjectParams) (GetProjectRow, error)
	GetProposal(ctx context.Context, arg GetProposalParams) (GetProposalRow, error)
	GetRecurringService(ctx context.Context, arg GetRecurringServiceParams) (GetRecurringServiceRow, error)
	GetResearch(ctx context.Context, arg GetResearchParams) (ResearchRecord, error)
	GetRevenue(ctx context.Context, arg GetRevenueParams) (Revenue, error)
	GetTemplate(ctx context.Context, arg GetTemplateParams) (OutreachTemplate, error)
	LatestAIAnalysis(ctx context.Context, arg LatestAIAnalysisParams) (AiAnalysis, error)
	LeadsForDashboard(ctx context.Context, userID uuid.UUID) ([]Lead, error)
	ListActivities(ctx context.Context, arg ListActivitiesParams) ([]ListActivitiesRow, error)
	ListClients(ctx context.Context, arg ListClientsParams) ([]ListClientsRow, error)
	ListCompanies(ctx context.Context, arg ListCompaniesParams) ([]Company, error)
	ListContacts(ctx context.Context, arg ListContactsParams) ([]Contact, error)
	ListContactsByCompany(ctx context.Context, arg ListContactsByCompanyParams) ([]Contact, error)
	ListFollowUps(ctx context.Context, arg ListFollowUpsParams) ([]ListFollowUpsRow, error)
	ListLeads(ctx context.Context, arg ListLeadsParams) ([]ListLeadsRow, error)
	ListNotifications(ctx context.Context, arg ListNotificationsParams) ([]Notification, error)
	ListProjects(ctx context.Context, arg ListProjectsParams) ([]ListProjectsRow, error)
	ListProposals(ctx context.Context, arg ListProposalsParams) ([]ListProposalsRow, error)
	ListRecurringServices(ctx context.Context, arg ListRecurringServicesParams) ([]ListRecurringServicesRow, error)
	ListResearch(ctx context.Context, arg ListResearchParams) ([]ResearchRecord, error)
	ListRevenues(ctx context.Context, arg ListRevenuesParams) ([]Revenue, error)
	ListTemplates(ctx context.Context, arg ListTemplatesParams) ([]OutreachTemplate, error)
	ListUserIDs(ctx context.Context) ([]uuid.UUID, error)
	MarkAllNotificationsRead(ctx context.Context, userID uuid.UUID) error
	MarkNotificationRead(ctx context.Context, arg MarkNotificationReadParams) (Notification, error)
	PipelineByStatus(ctx context.Context, userID uuid.UUID) ([]PipelineByStatusRow, error)
	ProposalsNearExpiry(ctx context.Context, userID uuid.UUID) ([]ProposalsNearExpiryRow, error)
	RecentActivities(ctx context.Context, arg RecentActivitiesParams) ([]RecentActivitiesRow, error)
	RecentLeads(ctx context.Context, arg RecentLeadsParams) ([]Lead, error)
	RecurringUpcomingBilling(ctx context.Context, userID uuid.UUID) ([]RecurringUpcomingBillingRow, error)
	RevenueMonthly(ctx context.Context, userID uuid.UUID) ([]RevenueMonthlyRow, error)
	RevenueMonthlyMRR(ctx context.Context, userID uuid.UUID) ([]RevenueMonthlyMRRRow, error)
	SearchActivities(ctx context.Context, arg SearchActivitiesParams) ([]SearchActivitiesRow, error)
	SearchClients(ctx context.Context, arg SearchClientsParams) ([]SearchClientsRow, error)
	SearchContacts(ctx context.Context, arg SearchContactsParams) ([]Contact, error)
	SearchProjects(ctx context.Context, arg SearchProjectsParams) ([]SearchProjectsRow, error)
	SearchRecurring(ctx context.Context, arg SearchRecurringParams) ([]SearchRecurringRow, error)
	SearchResearch(ctx context.Context, arg SearchResearchParams) ([]ResearchRecord, error)
	UnreadNotificationCount(ctx context.Context, userID uuid.UUID) (int32, error)
	UpdateClient(ctx context.Context, arg UpdateClientParams) (Client, error)
	UpdateCompany(ctx context.Context, arg UpdateCompanyParams) (Company, error)
	UpdateContact(ctx context.Context, arg UpdateContactParams) (Contact, error)
	UpdateFollowUp(ctx context.Context, arg UpdateFollowUpParams) (FollowUp, error)
	UpdateLead(ctx context.Context, arg UpdateLeadParams) (Lead, error)
	UpdateLeadStatus(ctx context.Context, arg UpdateLeadStatusParams) (Lead, error)
	UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error)
	UpdateProposal(ctx context.Context, arg UpdateProposalParams) (Proposal, error)
	UpdateRecurringService(ctx context.Context, arg UpdateRecurringServiceParams) (RecurringService, error)
	UpdateResearch(ctx context.Context, arg UpdateResearchParams) (ResearchRecord, error)
	UpdateTemplate(ctx context.Context, arg UpdateTemplateParams) (OutreachTemplate, error)
}

var _ Querier = (*Queries)(nil)
