// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: recurring.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const activeRecurringForMRR = `-- name: ActiveRecurringForMRR :many
SELECT amount, billing_cycle FROM recurring_services WHERE user_id = $1 AND status = 'active'
`

type ActiveRecurringForMRRRow struct {
	Amount       pgtype.Numeric
	BillingCycle string
}

func (q *Queries) ActiveRecurringForMRR(ctx context.Context, userID uuid.UUID) ([]ActiveRecurringForMRRRow, error) {
	rows, err := q.db.Query(ctx, activeRecurringForMRR, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ActiveRecurringForMRRRow
	for rows.Next() {
		var i ActiveRecurringForMRRRow
		if err := rows.Scan(&i.Amount, &i.BillingCycle); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createRecurringService = `-- name: CreateRecurringService :one
INSERT INTO recurring_services (user_id, client_id, project_id, name, amount, billing_cycle, start_date, next_billing_date, status, notes)
VALUES ($1, $2, $7, $3, $4, $5, $8, $9, $6, $10)
RETURNING id, user_id, client_id, project_id, name, amount, billing_cycle, start_date, next_billing_date, status, notes, created_at, updated_at
`

type CreateRecurringServiceParams struct {
	UserID          uuid.UUID
	ClientID        uuid.UUID
	Name            string
	Amount          pgtype.Numeric
	BillingCycle    string
	Status          string
	ProjectID       *uuid.UUID
	StartDate       pgtype.Date
	NextBillingDate pgtype.Date
	Notes           pgtype.Text
}

func (q *Queries) CreateRecurringService(ctx context.Context, arg CreateRecurringServiceParams) (RecurringService, error) {
	row := q.db.QueryRow(ctx, createRecurringService,
		arg.UserID,
		arg.ClientID,
		arg.Name,
		arg.Amount,
		arg.BillingCycle,
		arg.Status,
		arg.ProjectID,
		arg.StartDate,
		arg.NextBillingDate,
		arg.Notes,
	)
	var i RecurringService
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ClientID,
		&i.ProjectID,
		&i.Name,
		&i.Amount,
		&i.BillingCycle,
		&i.StartDate,
		&i.NextBillingDate,
		&i.Status,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteRecurringService = `-- name: DeleteRecurringService :exec
DELETE FROM recurring_services WHERE id = $1 AND user_id = $2
`

type DeleteRecurringServiceParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteRecurringService(ctx context.Context, arg DeleteRecurringServiceParams) error {
	_, err := q.db.Exec(ctx, deleteRecurringService, arg.ID, arg.UserID)
	return err
}

const getRecurringService = `-- name: GetRecurringService :one
SELECT r.id, r.user_id, r.client_id, r.project_id, r.name, r.amount, r.billing_cycle, r.start_date, r.next_billing_date, r.status, r.notes, r.created_at, r.updated_at, c.name AS client_company
FROM recurring_services r
JOIN clients cl ON cl.id = r.client_id
JOIN companies c ON c.id = cl.company_id
WHERE r.id = $1 AND r.user_id = $2
`

type GetRecurringServiceParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

type GetRecurringServiceRow struct {
	ID              uuid.UUID
	UserID          uuid.UUID
	ClientID        uuid.UUID
	ProjectID       *uuid.UUID
	Name            string
	Amount          pgtype.Numeric
	BillingCycle    string
	StartDate       pgtype.Date
	NextBillingDate pgtype.Date
	Status          string
	Notes           pgtype.Text
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	ClientCompany   string
}

func (q *Queries) GetRecurringService(ctx context.Context, arg GetRecurringServiceParams) (GetRecurringServiceRow, error) {
	row := q.db.QueryRow(ctx, getRecurringService, arg.ID, arg.UserID)
	var i GetRecurringServiceRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ClientID,
		&i.ProjectID,
		&i.Name,
		&i.Amount,
		&i.BillingCycle,
		&i.StartDate,
		&i.NextBillingDate,
		&i.Status,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClientCompany,
	)
	return i, err
}

const listRecurringServices = `-- name: ListRecurringServices :many
SELECT r.id, r.user_id, r.client_id, r.project_id, r.name, r.amount, r.billing_cycle, r.start_date, r.next_billing_date, r.status, r.notes, r.created_at, r.updated_at, c.name AS client_company
FROM recurring_services r
JOIN clients cl ON cl.id = r.client_id
JOIN companies c ON c.id = cl.company_id
WHERE r.user_id = $1
  AND ($4::text IS NULL OR r.status = $4)
  AND ($5::uuid IS NULL OR r.client_id = $5)
ORDER BY r.created_at DESC
LIMIT $2 OFFSET $3
`

type ListRecurringServicesParams struct {
	UserID   uuid.UUID
	Limit    int32
	Offset   int32
	Status   pgtype.Text
	ClientID *uuid.UUID
}

type ListRecurringServicesRow struct {
	ID              uuid.UUID
	UserID          uuid.UUID
	ClientID        uuid.UUID
	ProjectID       *uuid.UUID
	Name            string
	Amount          pgtype.Numeric
	BillingCycle    string
	StartDate       pgtype.Date
	NextBillingDate pgtype.Date
	Status          string
	Notes           pgtype.Text
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	ClientCompany   string
}

func (q *Queries) ListRecurringServices(ctx context.Context, arg ListRecurringServicesParams) ([]ListRecurringServicesRow, error) {
	rows, err := q.db.Query(ctx, listRecurringServices,
		arg.UserID,
		arg.Limit,
		arg.Offset,
		arg.Status,
		arg.ClientID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRecurringServicesRow
	for rows.Next() {
		var i ListRecurringServicesRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ClientID,
			&i.ProjectID,
			&i.Name,
			&i.Amount,
			&i.BillingCycle,
			&i.StartDate,
			&i.NextBillingDate,
			&i.Status,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ClientCompany,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recurringUpcomingBilling = `-- name: RecurringUpcomingBilling :many
SELECT r.id, r.user_id, r.client_id, r.project_id, r.name, r.amount, r.billing_cycle, r.start_date, r.next_billing_date, r.status, r.notes, r.created_at, r.updated_at, c.name AS client_company
FROM recurring_services r
JOIN clients cl ON cl.id = r.client_id
JOIN companies c ON c.id = cl.company_id
WHERE r.user_id = $1 AND r.status = 'active'
  AND r.next_billing_date IS NOT NULL
  AND r.next_billing_date BETWEEN CURRENT_DATE AND CURRENT_DATE + INTERVAL '5 days'
ORDER BY r.next_billing_date ASC LIMIT 20
`

type RecurringUpcomingBillingRow struct {
	ID              uuid.UUID
	UserID          uuid.UUID
	ClientID        uuid.UUID
	ProjectID       *uuid.UUID
	Name            string
	Amount          pgtype.Numeric
	BillingCycle    string
	StartDate       pgtype.Date
	NextBillingDate pgtype.Date
	Status          string
	Notes           pgtype.Text
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	ClientCompany   string
}

func (q *Queries) RecurringUpcomingBilling(ctx context.Context, userID uuid.UUID) ([]RecurringUpcomingBillingRow, error) {
	rows, err := q.db.Query(ctx, recurringUpcomingBilling, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RecurringUpcomingBillingRow
	for rows.Next() {
		var i RecurringUpcomingBillingRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ClientID,
			&i.ProjectID,
			&i.Name,
			&i.Amount,
			&i.BillingCycle,
			&i.StartDate,
			&i.NextBillingDate,
			&i.Status,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ClientCompany,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchRecurring = `-- name: SearchRecurring :many
SELECT r.id, r.user_id, r.client_id, r.project_id, r.name, r.amount, r.billing_cycle, r.start_date, r.next_billing_date, r.status, r.notes, r.created_at, r.updated_at, c.name AS client_company
FROM recurring_services r
JOIN clients cl ON cl.id = r.client_id
JOIN companies c ON c.id = cl.company_id
WHERE r.user_id = $1 AND r.name ILIKE '%' || $2 || '%'
ORDER BY r.created_at DESC LIMIT 10
`

type SearchRecurringParams struct {
	UserID  uuid.UUID
	Column2 pgtype.Text
}

type SearchRecurringRow struct {
	ID              uuid.UUID
	UserID          uuid.UUID
	ClientID        uuid.UUID
	ProjectID       *uuid.UUID
	Name            string
	Amount          pgtype.Numeric
	BillingCycle    string
	StartDate       pgtype.Date
	NextBillingDate pgtype.Date
	Status          string
	Notes           pgtype.Text
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	ClientCompany   string
}

func (q *Queries) SearchRecurring(ctx context.Context, arg SearchRecurringParams) ([]SearchRecurringRow, error) {
	rows, err := q.db.Query(ctx, searchRecurring, arg.UserID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchRecurringRow
	for rows.Next() {
		var i SearchRecurringRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ClientID,
			&i.ProjectID,
			&i.Name,
			&i.Amount,
			&i.BillingCycle,
			&i.StartDate,
			&i.NextBillingDate,
			&i.Status,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ClientCompany,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRecurringService = `-- name: UpdateRecurringService :one
UPDATE recurring_services SET
  name              = COALESCE($1, name),
  amount            = COALESCE($2, amount),
  billing_cycle     = COALESCE($3, billing_cycle),
  start_date        = COALESCE($4, start_date),
  next_billing_date = COALESCE($5, next_billing_date),
  status            = COALESCE($6, status),
  notes             = COALESCE($7, notes),
  updated_at        = now()
WHERE id = $8 AND user_id = $9
RETURNING id, user_id, client_id, project_id, name, amount, billing_cycle, start_date, next_billing_date, status, notes, created_at, updated_at
`

type UpdateRecurringServiceParams struct {
	Name            pgtype.Text
	Amount          pgtype.Numeric
	BillingCycle    pgtype.Text
	StartDate       pgtype.Date
	NextBillingDate pgtype.Date
	Status          pgtype.Text
	Notes           pgtype.Text
	ID              uuid.UUID
	UserID          uuid.UUID
}

func (q *Queries) UpdateRecurringService(ctx context.Context, arg UpdateRecurringServiceParams) (RecurringService, error) {
	row := q.db.QueryRow(ctx, updateRecurringService,
		arg.Name,
		arg.Amount,
		arg.BillingCycle,
		arg.StartDate,
		arg.NextBillingDate,
		arg.Status,
		arg.Notes,
		arg.ID,
		arg.UserID,
	)
	var i RecurringService
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ClientID,
		&i.ProjectID,
		&i.Name,
		&i.Amount,
		&i.BillingCycle,
		&i.StartDate,
		&i.NextBillingDate,
		&i.Status,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
