// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: research.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createResearch = `-- name: CreateResearch :one
INSERT INTO research_records (user_id, industry, location, keyword, company_name, website, description, pain_point, opportunity, service, priority, notes)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id, user_id, industry, location, keyword, company_name, website, description, pain_point, opportunity, service, priority, notes, created_at, updated_at
`

type CreateResearchParams struct {
	UserID      uuid.UUID
	Industry    pgtype.Text
	Location    pgtype.Text
	Keyword     pgtype.Text
	CompanyName pgtype.Text
	Website     pgtype.Text
	Description pgtype.Text
	PainPoint   pgtype.Text
	Opportunity pgtype.Text
	Service     pgtype.Text
	Priority    pgtype.Text
	Notes       pgtype.Text
}

func (q *Queries) CreateResearch(ctx context.Context, arg CreateResearchParams) (ResearchRecord, error) {
	row := q.db.QueryRow(ctx, createResearch,
		arg.UserID,
		arg.Industry,
		arg.Location,
		arg.Keyword,
		arg.CompanyName,
		arg.Website,
		arg.Description,
		arg.PainPoint,
		arg.Opportunity,
		arg.Service,
		arg.Priority,
		arg.Notes,
	)
	var i ResearchRecord
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Industry,
		&i.Location,
		&i.Keyword,
		&i.CompanyName,
		&i.Website,
		&i.Description,
		&i.PainPoint,
		&i.Opportunity,
		&i.Service,
		&i.Priority,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteResearch = `-- name: DeleteResearch :exec
DELETE FROM research_records WHERE id = $1 AND user_id = $2
`

type DeleteResearchParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteResearch(ctx context.Context, arg DeleteResearchParams) error {
	_, err := q.db.Exec(ctx, deleteResearch, arg.ID, arg.UserID)
	return err
}

const getResearch = `-- name: GetResearch :one
SELECT id, user_id, industry, location, keyword, company_name, website, description, pain_point, opportunity, service, priority, notes, created_at, updated_at FROM research_records WHERE id = $1 AND user_id = $2
`

type GetResearchParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) GetResearch(ctx context.Context, arg GetResearchParams) (ResearchRecord, error) {
	row := q.db.QueryRow(ctx, getResearch, arg.ID, arg.UserID)
	var i ResearchRecord
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Industry,
		&i.Location,
		&i.Keyword,
		&i.CompanyName,
		&i.Website,
		&i.Description,
		&i.PainPoint,
		&i.Opportunity,
		&i.Service,
		&i.Priority,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listResearch = `-- name: ListResearch :many
SELECT id, user_id, industry, location, keyword, company_name, website, description, pain_point, opportunity, service, priority, notes, created_at, updated_at FROM research_records
WHERE user_id = $1
  AND ($4::text IS NULL OR company_name ILIKE '%' || $4::text || '%')
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListResearchParams struct {
	UserID uuid.UUID
	Limit  int32
	Offset int32
	Search pgtype.Text
}

func (q *Queries) ListResearch(ctx context.Context, arg ListResearchParams) ([]ResearchRecord, error) {
	rows, err := q.db.Query(ctx, listResearch,
		arg.UserID,
		arg.Limit,
		arg.Offset,
		arg.Search,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ResearchRecord
	for rows.Next() {
		var i ResearchRecord
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Industry,
			&i.Location,
			&i.Keyword,
			&i.CompanyName,
			&i.Website,
			&i.Description,
			&i.PainPoint,
			&i.Opportunity,
			&i.Service,
			&i.Priority,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchResearch = `-- name: SearchResearch :many
SELECT id, user_id, industry, location, keyword, company_name, website, description, pain_point, opportunity, service, priority, notes, created_at, updated_at FROM research_records
WHERE user_id = $1 AND (company_name ILIKE '%' || $2 || '%' OR description ILIKE '%' || $2 || '%')
ORDER BY created_at DESC LIMIT 10
`

type SearchResearchParams struct {
	UserID  uuid.UUID
	Column2 pgtype.Text
}

func (q *Queries) SearchResearch(ctx context.Context, arg SearchResearchParams) ([]ResearchRecord, error) {
	rows, err := q.db.Query(ctx, searchResearch, arg.UserID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ResearchRecord
	for rows.Next() {
		var i ResearchRecord
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Industry,
			&i.Location,
			&i.Keyword,
			&i.CompanyName,
			&i.Website,
			&i.Description,
			&i.PainPoint,
			&i.Opportunity,
			&i.Service,
			&i.Priority,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateResearch = `-- name: UpdateResearch :one
UPDATE research_records SET
  industry    = COALESCE($1, industry),
  location    = COALESCE($2, location),
  keyword     = COALESCE($3, keyword),
  company_name= COALESCE($4, company_name),
  website     = COALESCE($5, website),
  description = COALESCE($6, description),
  pain_point  = COALESCE($7, pain_point),
  opportunity = COALESCE($8, opportunity),
  service     = COALESCE($9, service),
  priority    = COALESCE($10, priority),
  notes       = COALESCE($11, notes),
  updated_at  = now()
WHERE id = $12 AND user_id = $13
RETURNING id, user_id, industry, location, keyword, company_name, website, description, pain_point, opportunity, service, priority, notes, created_at, updated_at
`

type UpdateResearchParams struct {
	Industry    pgtype.Text
	Location    pgtype.Text
	Keyword     pgtype.Text
	CompanyName pgtype.Text
	Website     pgtype.Text
	Description pgtype.Text
	PainPoint   pgtype.Text
	Opportunity pgtype.Text
	Service     pgtype.Text
	Priority    pgtype.Text
	Notes       pgtype.Text
	ID          uuid.UUID
	UserID      uuid.UUID
}

func (q *Queries) UpdateResearch(ctx context.Context, arg UpdateResearchParams) (ResearchRecord, error) {
	row := q.db.QueryRow(ctx, updateResearch,
		arg.Industry,
		arg.Location,
		arg.Keyword,
		arg.CompanyName,
		arg.Website,
		arg.Description,
		arg.PainPoint,
		arg.Opportunity,
		arg.Service,
		arg.Priority,
		arg.Notes,
		arg.ID,
		arg.UserID,
	)
	var i ResearchRecord
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Industry,
		&i.Location,
		&i.Keyword,
		&i.CompanyName,
		&i.Website,
		&i.Description,
		&i.PainPoint,
		&i.Opportunity,
		&i.Service,
		&i.Priority,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
