// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: revenue.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countRevenues = `-- name: CountRevenues :one
SELECT COUNT(*) FROM revenues
WHERE user_id = $1
  AND ($2::text IS NULL OR type = $2)
  AND ($3::uuid IS NULL OR client_id = $3)
  AND ($4::date IS NULL OR occurred_at >= $4)
  AND ($5::date IS NULL OR occurred_at <= $5)
`

type CountRevenuesParams struct {
	UserID   uuid.UUID
	Type     pgtype.Text
	ClientID *uuid.UUID
	From     pgtype.Date
	To       pgtype.Date
}

func (q *Queries) CountRevenues(ctx context.Context, arg CountRevenuesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countRevenues,
		arg.UserID,
		arg.Type,
		arg.ClientID,
		arg.From,
		arg.To,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createRevenue = `-- name: CreateRevenue :one
INSERT INTO revenues (user_id, client_id, project_id, recurring_service_id, amount, type, occurred_at, notes)
VALUES ($1, $5, $6, $7, $2, $3, $4, $8)
RETURNING id, user_id, client_id, project_id, recurring_service_id, amount, type, occurred_at, notes, created_at
`

type CreateRevenueParams struct {
	UserID             uuid.UUID
	Amount             pgtype.Numeric
	Type               string
	OccurredAt         pgtype.Date
	ClientID           *uuid.UUID
	ProjectID          *uuid.UUID
	RecurringServiceID *uuid.UUID
	Notes              pgtype.Text
}

func (q *Queries) CreateRevenue(ctx context.Context, arg CreateRevenueParams) (Revenue, error) {
	row := q.db.QueryRow(ctx, createRevenue,
		arg.UserID,
		arg.Amount,
		arg.Type,
		arg.OccurredAt,
		arg.ClientID,
		arg.ProjectID,
		arg.RecurringServiceID,
		arg.Notes,
	)
	var i Revenue
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ClientID,
		&i.ProjectID,
		&i.RecurringServiceID,
		&i.Amount,
		&i.Type,
		&i.OccurredAt,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const deleteRevenue = `-- name: DeleteRevenue :exec
DELETE FROM revenues WHERE id = $1 AND user_id = $2
`

type DeleteRevenueParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteRevenue(ctx context.Context, arg DeleteRevenueParams) error {
	_, err := q.db.Exec(ctx, deleteRevenue, arg.ID, arg.UserID)
	return err
}

const getRevenue = `-- name: GetRevenue :one
SELECT id, user_id, client_id, project_id, recurring_service_id, amount, type, occurred_at, notes, created_at FROM revenues WHERE id = $1 AND user_id = $2
`

type GetRevenueParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) GetRevenue(ctx context.Context, arg GetRevenueParams) (Revenue, error) {
	row := q.db.QueryRow(ctx, getRevenue, arg.ID, arg.UserID)
	var i Revenue
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ClientID,
		&i.ProjectID,
		&i.RecurringServiceID,
		&i.Amount,
		&i.Type,
		&i.OccurredAt,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const listRevenues = `-- name: ListRevenues :many
SELECT id, user_id, client_id, project_id, recurring_service_id, amount, type, occurred_at, notes, created_at FROM revenues
WHERE user_id = $1
  AND ($4::text IS NULL OR type = $4)
  AND ($5::uuid IS NULL OR client_id = $5)
  AND ($6::date IS NULL OR occurred_at >= $6)
  AND ($7::date IS NULL OR occurred_at <= $7)
ORDER BY occurred_at DESC, created_at DESC
LIMIT $2 OFFSET $3
`

type ListRevenuesParams struct {
	UserID   uuid.UUID
	Limit    int32
	Offset   int32
	Type     pgtype.Text
	ClientID *uuid.UUID
	From     pgtype.Date
	To       pgtype.Date
}

func (q *Queries) ListRevenues(ctx context.Context, arg ListRevenuesParams) ([]Revenue, error) {
	rows, err := q.db.Query(ctx, listRevenues,
		arg.UserID,
		arg.Limit,
		arg.Offset,
		arg.Type,
		arg.ClientID,
		arg.From,
		arg.To,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Revenue
	for rows.Next() {
		var i Revenue
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ClientID,
			&i.ProjectID,
			&i.RecurringServiceID,
			&i.Amount,
			&i.Type,
			&i.OccurredAt,
			&i.Notes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revenueMonthly = `-- name: RevenueMonthly :many
SELECT date_trunc('month', occurred_at)::date::text AS month, COALESCE(SUM(amount),0)::float8 AS total
FROM revenues WHERE user_id = $1 GROUP BY 1 ORDER BY 1 DESC LIMIT 24
`

type RevenueMonthlyRow struct {
	Month string
	Total float64
}

func (q *Queries) RevenueMonthly(ctx context.Context, userID uuid.UUID) ([]RevenueMonthlyRow, error) {
	rows, err := q.db.Query(ctx, revenueMonthly, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RevenueMonthlyRow
	for rows.Next() {
		var i RevenueMonthlyRow
		if err := rows.Scan(&i.Month, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revenueMonthlyMRR = `-- name: RevenueMonthlyMRR :many
SELECT date_trunc('month', occurred_at)::date::text AS month, COALESCE(SUM(amount),0)::float8 AS total
FROM revenues
WHERE user_id = $1 AND type = 'recurring'
GROUP BY 1 ORDER BY 1 DESC LIMIT 24
`

type RevenueMonthlyMRRRow struct {
	Month string
	Total float64
}

func (q *Queries) RevenueMonthlyMRR(ctx context.Context, userID uuid.UUID) ([]RevenueMonthlyMRRRow, error) {
	rows, err := q.db.Query(ctx, revenueMonthlyMRR, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RevenueMonthlyMRRRow
	for rows.Next() {
		var i RevenueMonthlyMRRRow
		if err := rows.Scan(&i.Month, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
