// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: templates.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createTemplate = `-- name: CreateTemplate :one
INSERT INTO outreach_templates (user_id, name, category, channel, body)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, name, category, channel, body, created_at, updated_at
`

type CreateTemplateParams struct {
	UserID   uuid.UUID
	Name     string
	Category string
	Channel  string
	Body     string
}

func (q *Queries) CreateTemplate(ctx context.Context, arg CreateTemplateParams) (OutreachTemplate, error) {
	row := q.db.QueryRow(ctx, createTemplate,
		arg.UserID,
		arg.Name,
		arg.Category,
		arg.Channel,
		arg.Body,
	)
	var i OutreachTemplate
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Category,
		&i.Channel,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTemplate = `-- name: DeleteTemplate :exec
DELETE FROM outreach_templates WHERE id = $1 AND user_id = $2
`

type DeleteTemplateParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteTemplate(ctx context.Context, arg DeleteTemplateParams) error {
	_, err := q.db.Exec(ctx, deleteTemplate, arg.ID, arg.UserID)
	return err
}

const getTemplate = `-- name: GetTemplate :one
SELECT id, user_id, name, category, channel, body, created_at, updated_at FROM outreach_templates WHERE id = $1 AND user_id = $2
`

type GetTemplateParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) GetTemplate(ctx context.Context, arg GetTemplateParams) (OutreachTemplate, error) {
	row := q.db.QueryRow(ctx, getTemplate, arg.ID, arg.UserID)
	var i OutreachTemplate
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Category,
		&i.Channel,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTemplates = `-- name: ListTemplates :many
SELECT id, user_id, name, category, channel, body, created_at, updated_at FROM outreach_templates
WHERE user_id = $1
  AND ($4::text IS NULL OR category = $4)
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListTemplatesParams struct {
	UserID   uuid.UUID
	Limit    int32
	Offset   int32
	Category pgtype.Text
}

func (q *Queries) ListTemplates(ctx context.Context, arg ListTemplatesParams) ([]OutreachTemplate, error) {
	rows, err := q.db.Query(ctx, listTemplates,
		arg.UserID,
		arg.Limit,
		arg.Offset,
		arg.Category,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OutreachTemplate
	for rows.Next() {
		var i OutreachTemplate
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Category,
			&i.Channel,
			&i.Body,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTemplate = `-- name: UpdateTemplate :one
UPDATE outreach_templates SET
  name       = COALESCE($1, name),
  category   = COALESCE($2, category),
  channel    = COALESCE($3, channel),
  body       = COALESCE($4, body),
  updated_at = now()
WHERE id = $5 AND user_id = $6
RETURNING id, user_id, name, category, channel, body, created_at, updated_at
`

type UpdateTemplateParams struct {
	Name     pgtype.Text
	Category pgtype.Text
	Channel  pgtype.Text
	Body     pgtype.Text
	ID       uuid.UUID
	UserID   uuid.UUID
}

func (q *Queries) UpdateTemplate(ctx context.Context, arg UpdateTemplateParams) (OutreachTemplate, error) {
	row := q.db.QueryRow(ctx, updateTemplate,
		arg.Name,
		arg.Category,
		arg.Channel,
		arg.Body,
		arg.ID,
		arg.UserID,
	)
	var i OutreachTemplate
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Category,
		&i.Channel,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
